### PR TITLE
Update IFramePreviewView.tsx

### PR DESCRIPTION
**Pull request by henrikfischer**
Vercel build is failing because of wrong use of client

### CODE REVIEW

**Comment by snorrees** [comment]
Hi, thanks for the PR!

What exactly is the build error in the original code? This component is unused, but provided there as an example (usage instructions in readme).

We recommend using useClient in  studio components (which this is), because that accounts for studios with multiple workspaces, so providing the original error would be useful to investigate this further.

**Comment by kevinorin** [comment]
@henrikfischer updated file resolved the Vercel build error for me as well. 
Screen Shot 2023-03-02 at 8 51 32 PM

**Comment by snorrees** [comment]
I am unable to reproduce this, but realized that there where a couple of issues:

* typos in the preview docs using wrong imports
* appDir was set to true in next config

This is fixed on main now.

**Comment by snorrees** [comment]
I'm closing this PR, but feel free to reopen it if there is still a problem.
If you do, please include the steps you took after running the template, as it would be really useful in reproducing the original  issue.

**Pull request closed without merging**
